const eventHub = document.querySelector(".container")
export const ColorButtons = () => {
  return `
  <article class="colors">
    <fieldset>
    <legend>Background Colors</legend>

    <div class="flexVertical">
      <button id="btnTheme--red" value="red">Red</button>
      <button id="btnTheme--purple" value="purple">Purple</button>
      <button id="btnTheme--blue" value="blue">Blue</button>
      <button id="btnTheme--green" value="green">Green</button>
    </div>
    </fieldset>
  </article>
  `
}

eventHub.addEventListener("change", changeEvent => {
  // If the change event was generated by the radio buttons...
  if (changeEvent.target.id.contains("btnTheme--")) {
    const selectedcolor = changeEvent.target.value

    // Generate a new custom message that a color was selected
    const message = new CustomEvent("colorSelected", {
      detail: {
        color: selectedcolor,
      },
    })

    // Dispatch custom message to event hub
    eventHub.dispatchEvent(message)
  }
})
